GET http://localhost:3003/api/blogs
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImJheW9zZWd1biIsImlkIjoiNjU0ZmM3ODZiYWNhNjdiY2FjZWJmM2YxIiwiaWF0IjoxNzAwMDk5OTgwLCJleHAiOjE3MDAxMDM1ODB9.9ktSMlrRAxBoiAzoiWjEGYQ2OmQvUeHW3znE1VIZbYY
